// SPDX-License-Identifier: BUSL-1.1

package openapi_test

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/MustardSeedNetworks/foundation/pkg/httpserver/route"
	"github.com/MustardSeedNetworks/foundation/pkg/httpserver/route/openapi"
)

const niacHeader = "# GENERATED by `make openapi` (cmd/niac-openapi) — do not edit.\n" +
	"# Paths and their policy come from the capability registry\n" +
	"# (internal/api/route.go); prose and bodies from docs/openapi-source.yaml.\n"

func readJSON(t *testing.T, name string, v any) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "niac", name))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(data, v); err != nil {
		t.Fatalf("%s: %v", name, err)
	}
}

// TestGenerateReproducesNiac is the lift's acceptance: fed niac's own
// registry, source and error schema, the shared emitter writes niac's
// committed document byte for byte.
func TestGenerateReproducesNiac(t *testing.T) {
	var routes []route.Policy
	readJSON(t, "routes.json", &routes)
	var errSchema map[string]any
	readJSON(t, "error-schema.json", &errSchema)
	source, err := os.ReadFile(filepath.Join("testdata", "niac", "openapi-source.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	want, err := os.ReadFile(filepath.Join("testdata", "niac", "openapi.yaml"))
	if err != nil {
		t.Fatal(err)
	}

	got, err := openapi.Generate(source, routes, openapi.Options{
		Header:      niacHeader,
		ErrorSchema: errSchema,
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !bytes.Equal(got, want) {
		gotLines, wantLines := bytes.Split(got, []byte("\n")), bytes.Split(want, []byte("\n"))
		for i := range min(len(gotLines), len(wantLines)) {
			if !bytes.Equal(gotLines[i], wantLines[i]) {
				t.Fatalf("output differs at line %d:\n got: %s\nwant: %s", i+1, gotLines[i], wantLines[i])
			}
		}
		t.Fatalf("output length differs: got %d lines, want %d", len(gotLines), len(wantLines))
	}
}
